### ISSUE TITLE
A rule with equivalent dependencies is enqueued too many times

### ISSUE THREAD

**Issue by martin-danhier** [norswap/uranium#3] opened 2022-03-09 16:19 UTC
Hello again,

Thank you for merging my commit !

I think I found another bug while testing the update on my Sigh implementation.
It also occurs when two dependencies are the same (it's actually at the same place than the other one, and was introduced in the update):

```java
// Retrieve their declarations
DeclarationNode leftDecl = left.decl();
DeclarationNode rightDecl = right.decl();

// Retrieve their scopes
R.rule()
    .using(leftDecl.attr("scope"), rightDecl.attr("scope"))
    .by(r2 -> {
        Scope leftScope = r2.get(0);
        Scope rightScope = r2.get(1);

        // [...] find operators in the scopes and set the expression type (other rules are created)
    });
```

According to my analysis, here is what happens:

- In the `Reactor.register` function, the `for` loop iterates over dependencies (here two iterations)
- For each dependency, the `rule.supply` function is called
- In the `rule.supply`, for each dependency, the attribute is checked to avoid the problem of the previous issue. Here, both attributes match since they are equivalent, so the code inside the `if` is ran for each dependency.
- Each time a non-null attribute is set, the `unsatisfied` counter decrements, and thus reaches 0 when storing the value in the second dependency. Since the counter is 0, the rule is enqueued.
- But then, another iteration executes in the `reactor.register` function, which calls the `rule.supply`, which also runs two iterations to check the value. For both iterations, since the counter is 0, the rule is enqueued again.
- At the end, the rule was thus enqueued three times instead of once.
- This causes the rule code to be executed several time even though no redefinition was intended, and in the end triggers attribute redefinition in sub rules which crash the program with `"attempting to redefine: ..."`

Maybe the `register` function (and other functions iterating over dependencies to supply attributes, like `supplyToDependents`) should stop iterating over dependencies if `unsatisfied` is 0 ?

**Comment by norswap** [comment] 2022-03-10 14:33
Seems like a good analysis. I don't get why the rule is enqueued thrice though — seems it's like only twice?

I think a cleaner fix would be to check if the new value is equivalent to the old value in `Rule#supply` and to exit early in that case.

**Comment by martin-danhier** [comment] 2022-03-10 15:52
Thank you for your quick answer,

It is enqueued three times because the `unsatisifed` counter is decremented at the beginning of the iteration:

```java
if (old == null)
    -- unsatisfied;
if (unsatisfied == 0)
    // In case of redefinition, the rule could fire multiple times.
    // This is intended behaviour.
    reactor.enqueue(this);
```
Thus, at the second iteration, the value is decreased to 0 and the rule is enqueued, then at the third and fourth iteration, the counter is still 0 and the value is enqueued two more times.

I think the equivalence check could work !

**Comment by norswap** [comment] 2022-05-22 02:00
I see, so the scenario is as follows:
1. Define the rule as per the top snippet and assume 
    - `left == right` (so both attribute dependencies are the same)
    - `left.attr("scope")` already has its value set
2. This causes a call to `Rule#register`, whose loop does two iterations, hence calling `Rule#supply` twice
3. `Rule#supply` has itself a loop, ran twice each time (because the rule has two dependencies)
    - So in effect, the body of the loop is visited 4 times (2x2)
    - The first iteration doesn't do anything, has it only reduces `unsatisfied` from 2 to 1
    - But as explained above, each subsequent iteration enqueue the rule
4. Executing the rule multiple times causes its output to be redefined which causes an `attribute redefinition attempt`

> Maybe the register function (and other functions iterating over dependencies to supply attributes, like supplyToDependents) should stop iterating over dependencies if unsatisfied is 0 ?

This works if we don't allow redefinitions ever. If we allow redefinitions, then we want to set the attribute even though `unsatisfied` is already 0. I think redefinitions allow some useful use cases (incremental stuff) so I'd like to keep them in.

Possible solutions:

1. Just push the responsability of not having duplicate attributes on the user. I don't like this, it's not great UX.
2. De-duplicate attributes ourselves. This is tricky, because the dependencies are not only used to determine when a rule is ready to fire, but users also expect to access their values. If we do this we'd have to split the two concerns.
    - The split itself is confusing, suddenly there are two ways to access dependencies, which are almost always the same in practice, but in some edge case (duplicate dependencies) are different. This is also bad UX.
3. Don't re-enqueue if the old value is the same as the previous one. This solves the issue, but doesn't fix the muddled semantics. It does make sense to do this anyway though, since the computations should be deterministic, redefining to the same value should yield no change and so should be optimized away.

It's a little bit annoying that that the `supply` semantics are muddled. It was designed with the assumption it would only provide a value for one dependency, but this changed with the last fix. (2) would fix this, but I introduces a lot of complexity elsewhere, I don't think it's worth it.

(3) it is!

**Comment by norswap** [comment] 2022-05-22 03:23
Should be fixed by https://github.com/norswap/uranium/commit/465111436e5b947b8165303857f96e98576453b1
Feel free to reopen this issue if it isn't!

**Closed as completed by norswap** 2022-05-22 03:23 UTC
